package repository

import (
	"context"
	"fmt"
	"strings"

	"github.com/bloansbook/bloansbook-api/internal/models/suppliers"
	"github.com/bloansbook/bloansbook-api/pkg/config"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type SupplierRepository struct {
	db     *pgxpool.Pool
	config *config.Config
}

func NewSupplierRepository(db *pgxpool.Pool, config *config.Config) *SupplierRepository {
	return &SupplierRepository{db: db, config: config}
}

// supplierSelectQuery is the shared SELECT used by all read paths. The creator.*
// columns come from a LEFT JOIN on staff so responses can embed a creator summary.
const supplierSelectQuery = `
	SELECT
		s.id, s.supplier_id, s.name, s.phone, s.email, s.address, s.notes,
		s.category, s.currency, s.status, s.created_at, s.updated_at,
		creator.id AS creator_id, creator.staff_id AS creator_staff_id,
		creator.first_name AS creator_first_name, creator.last_name AS creator_last_name,
		creator.email AS creator_email, creator.phone AS creator_phone,
		creator.department AS creator_department, creator.job_title AS creator_job_title,
		creator.status AS creator_status
	FROM suppliers s
	LEFT JOIN staff creator ON s.created_by = creator.id
`

func (r *SupplierRepository) CountSuppliers(ctx context.Context) (int, error) {
	var count int
	err := r.db.QueryRow(ctx, `SELECT COUNT(*) FROM suppliers`).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("failed to count suppliers: %w", err)
	}
	return count, nil
}

// CreateSupplier inserts a new supplier. supplierID is generated by the caller
// (usecase) and createdBy is the authenticated staff member. currency and status
// are left to their DB defaults ('NGN' / 'active').
func (r *SupplierRepository) CreateSupplier(ctx context.Context, supplierID string, createdBy uuid.UUID, payload *suppliers.CreateSupplierPayload) (*suppliers.Supplier, error) {
	stmt := `
		INSERT INTO suppliers (
			supplier_id, name, phone, email, address, notes, category, created_by
		) VALUES (
			@supplier_id, @name, @phone, @email, @address, @notes, @category, @created_by
		) RETURNING id, supplier_id, name, phone, email, category, status, created_at, updated_at
	`

	var m suppliers.Supplier
	err := r.db.QueryRow(ctx, stmt, pgx.NamedArgs{
		"supplier_id": supplierID,
		"name":        payload.Name,
		"phone":       payload.Phone,
		"email":       payload.Email,
		"address":     payload.Address,
		"notes":       payload.Notes,
		"category":    payload.Category,
		"created_by":  createdBy,
	}).Scan(
		&m.ID, &m.SupplierID, &m.Name, &m.Phone, &m.Email,
		&m.Category, &m.Status, &m.CreatedAt, &m.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create supplier: %w", err)
	}
	return &m, nil
}

func (r *SupplierRepository) GetSupplierByID(ctx context.Context, id uuid.UUID) (*suppliers.Supplier, error) {
	stmt := supplierSelectQuery + `WHERE s.id = $1`

	var m suppliers.Supplier
	err := r.db.QueryRow(ctx, stmt, id).Scan(
		&m.ID, &m.SupplierID, &m.Name, &m.Phone, &m.Email, &m.Address, &m.Notes,
		&m.Category, &m.Currency, &m.Status, &m.CreatedAt, &m.UpdatedAt,
		&m.CreatorID, &m.CreatorStaffID,
		&m.CreatorFirstName, &m.CreatorLastName,
		&m.CreatorEmail, &m.CreatorPhone,
		&m.CreatorDepartment, &m.CreatorJobTitle, &m.CreatorStatus,
	)
	if err != nil {
		return nil, fmt.Errorf("supplier not found: %w", err)
	}
	return &m, nil
}

// GetAllSuppliers returns a filtered, sorted, paginated list of suppliers.
// All filter fields on SupplierFilter are optional — zero values are ignored.
func (r *SupplierRepository) GetAllSuppliers(ctx context.Context, f suppliers.SupplierFilter) ([]suppliers.Supplier, error) {
	sortColumn := map[string]string{
		"createdAt":  "s.created_at",
		"name":       "s.name",
		"supplierId": "s.supplier_id",
		"category":   "s.category",
		"status":     "s.status",
	}
	col, ok := sortColumn[f.SortBy]
	if !ok {
		col = "s.created_at"
	}

	order := "DESC"
	if strings.EqualFold(f.SortOrder, "asc") {
		order = "ASC"
	}

	args := pgx.NamedArgs{}
	where := ""

	if f.Search != "" {
		where += `
			AND (
				s.name        ILIKE '%' || @search || '%'
				OR s.supplier_id ILIKE '%' || @search || '%'
				OR s.phone       ILIKE '%' || @search || '%'
			)`
		args["search"] = f.Search
	}
	if f.Category != "" {
		where += ` AND s.category = @category`
		args["category"] = f.Category
	}
	if f.Status != "" {
		where += ` AND s.status = @status`
		args["status"] = f.Status
	}

	args["limit"] = f.Limit
	args["offset"] = f.Offset

	stmt := supplierSelectQuery +
		`WHERE 1=1` + where +
		` ORDER BY ` + col + ` ` + order +
		` LIMIT @limit OFFSET @offset`

	rows, err := r.db.Query(ctx, stmt, args)
	if err != nil {
		return nil, fmt.Errorf("failed to get all suppliers: %w", err)
	}
	defer rows.Close()

	var list []suppliers.Supplier
	for rows.Next() {
		var m suppliers.Supplier
		if err := rows.Scan(
			&m.ID, &m.SupplierID, &m.Name, &m.Phone, &m.Email, &m.Address, &m.Notes,
			&m.Category, &m.Currency, &m.Status, &m.CreatedAt, &m.UpdatedAt,
			&m.CreatorID, &m.CreatorStaffID,
			&m.CreatorFirstName, &m.CreatorLastName,
			&m.CreatorEmail, &m.CreatorPhone,
			&m.CreatorDepartment, &m.CreatorJobTitle, &m.CreatorStatus,
		); err != nil {
			return nil, fmt.Errorf("failed to scan supplier row: %w", err)
		}
		list = append(list, m)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating supplier rows: %w", err)
	}
	return list, nil
}

// UpdateSupplier applies a partial update. nil payload fields are left unchanged
// via COALESCE. supplier_id, currency and created_by are immutable here.
func (r *SupplierRepository) UpdateSupplier(ctx context.Context, id uuid.UUID, payload *suppliers.UpdateSupplierPayload) (*suppliers.Supplier, error) {
	stmt := `
		UPDATE suppliers SET
			name       = COALESCE(@name, name),
			phone      = COALESCE(@phone, phone),
			email      = COALESCE(@email, email),
			address    = COALESCE(@address, address),
			notes      = COALESCE(@notes, notes),
			category   = COALESCE(@category, category),
			status     = COALESCE(@status, status),
			updated_at = NOW()
		WHERE id = @id
		RETURNING id, supplier_id, name, phone, email, category, status, created_at, updated_at
	`

	var m suppliers.Supplier
	err := r.db.QueryRow(ctx, stmt, pgx.NamedArgs{
		"id":       id,
		"name":     payload.Name,
		"phone":    payload.Phone,
		"email":    payload.Email,
		"address":  payload.Address,
		"notes":    payload.Notes,
		"category": payload.Category,
		"status":   payload.Status,
	}).Scan(
		&m.ID, &m.SupplierID, &m.Name, &m.Phone, &m.Email,
		&m.Category, &m.Status, &m.CreatedAt, &m.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to update supplier: %w", err)
	}
	return &m, nil
}
