package repository

import (
	"context"
	"fmt"
	"strings"

	"github.com/bloansbook/bloansbook-api/internal/models/customers"
	"github.com/bloansbook/bloansbook-api/pkg/config"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type CustomerRepository struct {
	db     *pgxpool.Pool
	config *config.Config
}

func NewCustomerRepository(db *pgxpool.Pool, config *config.Config) *CustomerRepository {
	return &CustomerRepository{db: db, config: config}
}

// customerSelectQuery is the shared SELECT used by all read paths. The creator.*
// columns come from a LEFT JOIN on staff so responses can embed a creator summary.
const customerSelectQuery = `
	SELECT
		c.id, c.customer_id, c.name, c.phone, c.email, c.address, c.notes,
		c.type, c.currency, c.status, c.created_at, c.updated_at,
		creator.id AS creator_id, creator.staff_id AS creator_staff_id,
		creator.first_name AS creator_first_name, creator.last_name AS creator_last_name,
		creator.email AS creator_email, creator.phone AS creator_phone,
		creator.department AS creator_department, creator.job_title AS creator_job_title,
		creator.status AS creator_status
	FROM customers c
	LEFT JOIN staff creator ON c.created_by = creator.id
`

func (r *CustomerRepository) CountCustomers(ctx context.Context) (int, error) {
	var count int
	err := r.db.QueryRow(ctx, `SELECT COUNT(*) FROM customers`).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("failed to count customers: %w", err)
	}
	return count, nil
}

// CreateCustomer inserts a new customer. customerID is generated by the caller
// (usecase) and createdBy is the authenticated staff member. currency and status
// are left to their DB defaults ('NGN' / 'active').
func (r *CustomerRepository) CreateCustomer(ctx context.Context, customerID string, createdBy uuid.UUID, payload *customers.CreateCustomerPayload) (*customers.Customers, error) {
	stmt := `
		INSERT INTO customers (
			customer_id, name, phone, email, address, notes, type, created_by
		) VALUES (
			@customer_id, @name, @phone, @email, @address, @notes, @type, @created_by
		) RETURNING id, customer_id, name, phone, email, type, status, created_at, updated_at
	`

	var m customers.Customers
	err := r.db.QueryRow(ctx, stmt, pgx.NamedArgs{
		"customer_id": customerID,
		"name":        payload.Name,
		"phone":       payload.Phone,
		"email":       payload.Email,
		"address":     payload.Address,
		"notes":       payload.Notes,
		"type":        payload.Type,
		"created_by":  createdBy,
	}).Scan(
		&m.ID, &m.CustomerID, &m.Name, &m.Phone, &m.Email,
		&m.Type, &m.Status, &m.CreatedAt, &m.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create customer: %w", err)
	}
	return &m, nil
}

func (r *CustomerRepository) GetCustomerByID(ctx context.Context, id uuid.UUID) (*customers.Customers, error) {
	stmt := customerSelectQuery + `WHERE c.id = $1`

	var m customers.Customers
	err := r.db.QueryRow(ctx, stmt, id).Scan(
		&m.ID, &m.CustomerID, &m.Name, &m.Phone, &m.Email, &m.Address, &m.Notes,
		&m.Type, &m.Currency, &m.Status, &m.CreatedAt, &m.UpdatedAt,
		&m.CreatorID, &m.CreatorStaffID,
		&m.CreatorFirstName, &m.CreatorLastName,
		&m.CreatorEmail, &m.CreatorPhone,
		&m.CreatorDepartment, &m.CreatorJobTitle, &m.CreatorStatus,
	)
	if err != nil {
		return nil, fmt.Errorf("customer not found: %w", err)
	}
	return &m, nil
}

func (r *CustomerRepository) GetCustomerByCustomerID(ctx context.Context, customerID string) (*customers.Customers, error) {
	stmt := customerSelectQuery + `WHERE c.customer_id = $1`

	var m customers.Customers
	err := r.db.QueryRow(ctx, stmt, customerID).Scan(
		&m.ID, &m.CustomerID, &m.Name, &m.Phone, &m.Email, &m.Address, &m.Notes,
		&m.Type, &m.Currency, &m.Status, &m.CreatedAt, &m.UpdatedAt,
		&m.CreatorID, &m.CreatorStaffID,
		&m.CreatorFirstName, &m.CreatorLastName,
		&m.CreatorEmail, &m.CreatorPhone,
		&m.CreatorDepartment, &m.CreatorJobTitle, &m.CreatorStatus,
	)
	if err != nil {
		return nil, fmt.Errorf("customer not found: %w", err)
	}
	return &m, nil
}

// GetAllCustomers returns a filtered, sorted, paginated list of customers.
// All filter fields on CustomerFilter are optional — zero values are ignored.
func (r *CustomerRepository) GetAllCustomers(ctx context.Context, f customers.CustomerFilter) ([]customers.Customers, error) {
	sortColumn := map[string]string{
		"createdAt":  "c.created_at",
		"name":       "c.name",
		"customerId": "c.customer_id",
		"type":       "c.type",
		"status":     "c.status",
	}
	col, ok := sortColumn[f.SortBy]
	if !ok {
		col = "c.created_at"
	}

	order := "DESC"
	if strings.EqualFold(f.SortOrder, "asc") {
		order = "ASC"
	}

	args := pgx.NamedArgs{}
	where := ""

	if f.Search != "" {
		where += `
			AND (
				c.name        ILIKE '%' || @search || '%'
				OR c.customer_id ILIKE '%' || @search || '%'
				OR c.phone       ILIKE '%' || @search || '%'
			)`
		args["search"] = f.Search
	}
	if f.Type != "" {
		where += ` AND c.type = @type`
		args["type"] = f.Type
	}
	if f.Status != "" {
		where += ` AND c.status = @status`
		args["status"] = f.Status
	}

	args["limit"] = f.Limit
	args["offset"] = f.Offset

	stmt := customerSelectQuery +
		`WHERE 1=1` + where +
		` ORDER BY ` + col + ` ` + order +
		` LIMIT @limit OFFSET @offset`

	rows, err := r.db.Query(ctx, stmt, args)
	if err != nil {
		return nil, fmt.Errorf("failed to get all customers: %w", err)
	}
	defer rows.Close()

	var list []customers.Customers
	for rows.Next() {
		var m customers.Customers
		if err := rows.Scan(
			&m.ID, &m.CustomerID, &m.Name, &m.Phone, &m.Email, &m.Address, &m.Notes,
			&m.Type, &m.Currency, &m.Status, &m.CreatedAt, &m.UpdatedAt,
			&m.CreatorID, &m.CreatorStaffID,
			&m.CreatorFirstName, &m.CreatorLastName,
			&m.CreatorEmail, &m.CreatorPhone,
			&m.CreatorDepartment, &m.CreatorJobTitle, &m.CreatorStatus,
		); err != nil {
			return nil, fmt.Errorf("failed to scan customer row: %w", err)
		}
		list = append(list, m)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating customer rows: %w", err)
	}
	return list, nil
}

// UpdateCustomer applies a partial update. nil payload fields are left unchanged
// via COALESCE. customer_id, currency and created_by are immutable here.
func (r *CustomerRepository) UpdateCustomer(ctx context.Context, id uuid.UUID, payload *customers.UpdateCustomerPayload) (*customers.Customers, error) {
	stmt := `
		UPDATE customers SET
			name       = COALESCE(@name, name),
			phone      = COALESCE(@phone, phone),
			email      = COALESCE(@email, email),
			address    = COALESCE(@address, address),
			notes      = COALESCE(@notes, notes),
			type       = COALESCE(@type, type),
			status     = COALESCE(@status, status),
			updated_at = NOW()
		WHERE id = @id
		RETURNING id, customer_id, name, phone, email, type, status, created_at, updated_at
	`

	var m customers.Customers
	err := r.db.QueryRow(ctx, stmt, pgx.NamedArgs{
		"id":      id,
		"name":    payload.Name,
		"phone":   payload.Phone,
		"email":   payload.Email,
		"address": payload.Address,
		"notes":   payload.Notes,
		"type":    payload.Type,
		"status":  payload.Status,
	}).Scan(
		&m.ID, &m.CustomerID, &m.Name, &m.Phone, &m.Email,
		&m.Type, &m.Status, &m.CreatedAt, &m.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to update customer: %w", err)
	}
	return &m, nil
}
